#!/bin/python3

import sys

def diagonalDifference(n,a):
    f=0
    s=0
    for i in range(n):
        f+=a[i][i]
        s+=a[i][n-1-i]
    return(abs(f-s))
   
if __name__ == "__main__":
    n = int(input().strip())
    a = []
    for a_i in range(n):
        a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
        a.append(a_t)
    result = diagonalDifference(n,a)
    print(result)
